version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install && npm run build
      - run:
          name: Start Application
          command: npm index.js

workflows:
  version: 2
  run_now:
    jobs:
      - build
