version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash && source ~/.bashrc && nvm install 14 && cd multi && npm install
          name: Start Application
          command: npm index.js

workflows:
  version: 2
  run_now:
    jobs:
      - build
