version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:12x
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Start Application
          command: npm start

workflows:
  version: 2
  run_now:
    jobs:
      - build
